### ISSUE TITLE
Emphasised text in a list formatted wrong

### ISSUE THREAD

**Issue by ThomasHickman** [timlockridge/all-shades-of-blue-syntax#1]
The markdown document:

```markdown
- **bold** list item
```

is formatted as:

![image](https://cloud.githubusercontent.com/assets/6304200/23566610/971980f0-004a-11e7-99a2-27465740efb3.png)

Notice the asterisks seem to take up no room and therefore are overlayed on the word. This also happens with text formatted as italic

**Comment by timlockridge** [comment]
Thanks! I fixed this and published a new version. It should be resolved in 0.5.5
